<a href="https://colab.research.google.com/github/chohyungrae/Machine-Learning-Deep-Learning-Code-Learning/blob/master/array(%EB%B0%B0%EC%97%B4_%EC%97%B0%EC%8A%B5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# NumPy 패키지를 임포트


In [ ]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x
#1차원 배열 만들기, array함수에 리스트를 넣으면 배열로 변환

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(x)
# 타입확인

numpy.ndarray

In [ ]:
2 * x
# 2배 한 경우

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [ ]:
2 * a + b

array([12, 24, 36])

In [ ]:
a == 2

array([False,  True, False])

In [ ]:
b > 10

array([False,  True,  True])